language: python
jobs:
  include:
    - name: "Python 3.8.0 on Xenial Linux"
      python: 3.8
      before_script:
        - python3 -c "import pymatting"
        - python3 tests/download_images.py
    - name: "Python 3.7.4 on macOS"
      os: osx
      osx_image: xcode11.2
      language: shell
      before_script:
        - python3 -c "import pymatting"
        - python3 tests/download_images.py
    - name: "Python 3.8.0 on Windows"
      os: windows
      language: shell
      before_install:
        - choco install python --version 3.8.0
        - python -m pip install --upgrade pip
      before_script:
        - python -c "import pymatting"
        - python tests/download_images.py
      env: PATH=/c/Python38:/c/Python38/Scripts:$PATH
install:
  - pip3 install -r requirements.txt -r requirements_tests.txt
  - pip3 install .
before_script: flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics

script: pytest
